const school = [
    {
        "id": 1,
        "name_cn": "东京大学",
        "name_en": "University of Tokyo",
        "name_jp": "東京大学",
        "style_logo": "\/uploads\/20180816\/d24127a6f559624111adf383d5b4f799.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/1.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/1.png",
        "cityid": 3556,
        "address": "东京都文京区本乡7-3-1",
        "website": "http:\/\/www.u-kyoto.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 1,
        "rank_world": 34
    },
    {
        "id": 2,
        "name_cn": "京都大学",
        "name_en": "Kyoto Unviersity",
        "name_jp": "京都大学",
        "style_logo": "\/uploads\/20180816\/ffb4f3a0ef2c05c22778fe4dac66457c.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/2.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/2.png",
        "cityid": 3517,
        "address": "京都府京都市左京区吉田本町",
        "website": "http:\/\/www.kyoto-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 2,
        "rank_world": 37
    },
    {
        "id": 3,
        "name_cn": "大阪大学",
        "name_en": "Osaka University",
        "name_jp": "大阪大学",
        "style_logo": "\/uploads\/20180816\/8a9e29a2e08b306c386fbc760ed3ddde.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/3.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/3.png",
        "cityid": 3518,
        "address": "大阪府吹田市山田丘１−１",
        "website": "http:\/\/www.osaka-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 4,
        "rank_world": 63
    },
    {
        "id": 4,
        "name_cn": "一桥大学",
        "name_en": "Hitotsubashi University",
        "name_jp": "一橋大学",
        "style_logo": "",
        "long_logo": "\/uploads\/schools\/long_logo\/4.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/4.png",
        "cityid": 3556,
        "address": "東京都国立市中２−１",
        "website": "http:\/\/www.hit-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 15,
        "rank_world": 480
    },
    {
        "id": 5,
        "name_cn": "东京工业大学",
        "name_en": "Tokyo Institute of Technology",
        "name_jp": "東京工業大学",
        "style_logo": "\/uploads\/20180821\/3586adc8d557e62e1822721123b855d4.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/5.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/5.png",
        "cityid": 3556,
        "address": "东京都目黒区大冈山2-12-1",
        "website": "http:\/\/www.titech.ac.jp\/",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 3,
        "rank_world": 56
    },
    {
        "id": 6,
        "name_cn": "东北大学",
        "name_en": "Tohoku University",
        "name_jp": "東北大学",
        "style_logo": "\/uploads\/20180821\/f8e1174a8669aa25a4925f4d445add30.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/6.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/6.png",
        "cityid": 3517,
        "address": "宮城県仙台市青葉区片平二丁目１−１",
        "website": "http:\/\/www.tohoku.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 5,
        "rank_world": 75
    },
    {
        "id": 7,
        "name_cn": "名古屋大学",
        "name_en": "Nagoya University",
        "name_jp": "名古屋大学",
        "style_logo": "\/uploads\/20180816\/37e9b5b15d8862910ec069d18074879b.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/7.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/7.png",
        "cityid": 3548,
        "address": "日本 愛知県名古屋市 昭和区鶴舞町",
        "website": "http:\/\/www.nagoya-u.ac.jp\/",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 6,
        "rank_world": 115
    },
    {
        "id": 8,
        "name_cn": "九州大学",
        "name_en": "Kyushu University",
        "name_jp": "九州大学",
        "style_logo": "\/uploads\/20180821\/49ca25134470a647d786af4b929e8bcc.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/8.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/8.png",
        "cityid": 3531,
        "address": "福岡県福岡市西区元冈744",
        "website": "http:\/\/www.kyushu-u.ac.jp\/",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 8,
        "rank_world": 135
    },
    {
        "id": 9,
        "name_cn": "筑波大学",
        "name_en": "University of Tsukuba",
        "name_jp": "筑波大学",
        "style_logo": "\/uploads\/20180816\/5bfc9717f9e4ff55cfe2737554be3ea8.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/9.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/9.png",
        "cityid": 3515,
        "address": "茨城県筑波市天王台１−１−１",
        "website": "http:\/\/www.tsukuba.ac.jp\/",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 11,
        "rank_world": 225
    },
    {
        "id": 10,
        "name_cn": "神户大学",
        "name_en": "Kobe University",
        "name_jp": "神戸大学",
        "style_logo": "",
        "long_logo": "\/uploads\/schools\/long_logo\/10.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/10.png",
        "cityid": 3520,
        "address": "兵庫県神戸市灘区六甲台町１−１",
        "website": "http:\/\/www.kobe-u.ac.jp\/",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 13,
        "rank_world": 369
    },
    {
        "id": 11,
        "name_cn": "庆应义塾大学",
        "name_en": "Keio University",
        "name_jp": "慶應義塾大学 ",
        "style_logo": "\/uploads\/20180821\/d2e6d166a1969548b2c85fc53acd9b38.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/11.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/11.png",
        "cityid": 3556,
        "address": "东京都港区三田二町目15番45号",
        "website": "http:\/\/www.keio.ac.jp",
        "nature_id": 94,
        "nature_name": "私立",
        "contact": "4000150170",
        "rank_local": 10,
        "rank_world": 216
    },
    {
        "id": 12,
        "name_cn": "早稻田大学",
        "name_en": "Waseda University",
        "name_jp": "早稲田大学 ",
        "style_logo": "\/uploads\/20180821\/898e1ae72484d3a0daa741f55b120a35.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/12.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/12.png",
        "cityid": 3556,
        "address": "<早稻田校区>东京都新宿区西早稻田1-6-1",
        "website": "http:\/\/www.waseda.jp",
        "nature_id": 94,
        "nature_name": "私立",
        "contact": "4000150170",
        "rank_local": 9,
        "rank_world": 201
    },
    {
        "id": 13,
        "name_cn": "北海道大学",
        "name_en": "Hokkaido University",
        "name_jp": "北海道大学",
        "style_logo": "\/uploads\/20180821\/e2c2da68f3c6876254d8b8a611be362c.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/13.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/13.png",
        "cityid": 3511,
        "address": "<札幌校区>北海道札幌市北区北8西5丁目",
        "website": "http:\/\/www.hokudai.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 7,
        "rank_world": 130
    },
    {
        "id": 14,
        "name_cn": "广岛大学",
        "name_en": "Hiroshima University",
        "name_jp": "広島大学",
        "style_logo": "\/uploads\/20180821\/4f15bf304684292a17807a08a1399c3a.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/14.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/14.png",
        "cityid": 3520,
        "address": "広島県東広島市 鏡山一丁目3番2号",
        "website": "http:\/\/www.hiroshima-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 12,
        "rank_world": 297
    },
    {
        "id": 15,
        "name_cn": "横滨国立大学",
        "name_en": "Yokohama National University",
        "name_jp": "横浜国立大学",
        "style_logo": "",
        "long_logo": "\/uploads\/schools\/long_logo\/15.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/15.png",
        "cityid": 3557,
        "address": "神奈川县横滨市保土谷区常盘台79-1",
        "website": "http:\/\/www.ynu.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 34,
        "rank_world": 700
    },
    {
        "id": 16,
        "name_cn": "千叶大学",
        "name_en": "Chiba University ",
        "name_jp": "千葉大学",
        "style_logo": "\/uploads\/20180821\/b07300a11f85e3acb1b576811b0b2028.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/16.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/16.png",
        "cityid": 3558,
        "address": "千叶县千叶市稻毛区弥生町1-33",
        "website": "http:\/\/www.chiba-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 16,
        "rank_world": 555
    },
    {
        "id": 17,
        "name_cn": "东京理科大学",
        "name_en": "Tokyo University of Science",
        "name_jp": "東京理科大学",
        "style_logo": "",
        "long_logo": "\/uploads\/schools\/long_logo\/17.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/17.png",
        "cityid": 3556,
        "address": "東京都新宿区神楽坂1-3",
        "website": "http:\/\/www.sut.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 30,
        "rank_world": 700
    },
    {
        "id": 18,
        "name_cn": "东京外国语大学",
        "name_en": "Tokyo University of Foreign Studies",
        "name_jp": "東京外国語大学",
        "style_logo": "\/uploads\/20180821\/4285095807424dd5da042f3bd5ca2acf.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/18.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/18.png",
        "cityid": 3556,
        "address": "东京都府中市朝日町3-11-1",
        "website": "http:\/\/www.tufs.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 50,
        "rank_world": 900
    },
    {
        "id": 19,
        "name_cn": "金泽大学",
        "name_en": "Kanezawa University",
        "name_jp": "金沢大学",
        "style_logo": "\/uploads\/20180821\/3e24a333f5923f1cd34ab996d1fc3569.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/19.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/19.png",
        "cityid": 3533,
        "address": "石川县 金泽市 角間町",
        "website": "http:\/\/www.kanazawa-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 19,
        "rank_world": 500
    },
    {
        "id": 20,
        "name_cn": "东京医科齿科大学",
        "name_en": "Tokyo Medical and Dental University",
        "name_jp": "東京医科歯科大学",
        "style_logo": "\/uploads\/20180821\/24f275cc26a05a6b9c7038843fdb07c5.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/20.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/20.png",
        "cityid": 3556,
        "address": "东京都文京区汤岛一丁目五番四十五号",
        "website": "http:\/\/www.tmd.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 14,
        "rank_world": 330
    },
    {
        "id": 21,
        "name_cn": "大阪市立大学",
        "name_en": "Osaka City University",
        "name_jp": "大阪市立大学",
        "style_logo": "",
        "long_logo": "\/uploads\/schools\/long_logo\/21.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/21.png",
        "cityid": 3518,
        "address": "住吉区杉本3−3−138",
        "website": "http:\/\/www.osaka-cu.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 22,
        "rank_world": 650
    },
    {
        "id": 22,
        "name_cn": "御茶水女子大学",
        "name_en": "Ochanomizu University",
        "name_jp": "お茶の水女子大学",
        "style_logo": "",
        "long_logo": "\/uploads\/schools\/long_logo\/22.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/22.png",
        "cityid": 3556,
        "address": "東京都文京区大塚2-1-1 ",
        "website": "http:\/\/www.ocha.ac.jp",
        "nature_id": 94,
        "nature_name": "私立",
        "contact": "4000150170",
        "rank_local": 39,
        "rank_world": 701
    },
    {
        "id": 23,
        "name_cn": "冈山大学",
        "name_en": "Okayama University ",
        "name_jp": "岡山大学",
        "style_logo": "\/uploads\/20180821\/c68e3f56e3d852bce9c93570b57fe91a.jpg",
        "long_logo": "",
        "sm_logo": "\/uploads\/schools\/sm_logo\/23.png",
        "cityid": 3511,
        "address": "岡山県岡山市北区津島中1丁目1－1",
        "website": "http:\/\/www.okayama-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 17,
        "rank_world": 410
    },
    {
        "id": 24,
        "name_cn": "熊本大学",
        "name_en": "Kumamoto University",
        "name_jp": "熊本大学",
        "style_logo": "\/uploads\/20180821\/2a49b4a6d3b468338abeb174bf002dd8.jpg",
        "long_logo": "",
        "sm_logo": "\/uploads\/schools\/sm_logo\/24.png",
        "cityid": 3511,
        "address": "熊本市中央区黒髪２−３９−１",
        "website": "http:\/\/www.kumamoto-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 20,
        "rank_world": 420
    },
    {
        "id": 25,
        "name_cn": "德岛大学",
        "name_en": "The University of Tokushima",
        "name_jp": "徳島大学",
        "style_logo": "",
        "long_logo": "",
        "sm_logo": "\/uploads\/schools\/sm_logo\/25.png",
        "cityid": 1,
        "address": "德岛县,徳島市新藏町2丁目24番地",
        "website": "http:\/\/www.tokushima-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 75,
        "rank_world": 990
    },
    {
        "id": 26,
        "name_cn": "首都大学东京",
        "name_en": "Tokyo Metropolitan University",
        "name_jp": "首都大学東京",
        "style_logo": "",
        "long_logo": "\/uploads\/schools\/long_logo\/26.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/26.png",
        "cityid": 3556,
        "address": "东京都八王子市南大沢1-1 ",
        "website": "http:\/\/www.tmu.ac.jp",
        "nature_id": 93,
        "nature_name": "公立",
        "contact": "4000150170",
        "rank_local": 26,
        "rank_world": 470
    },
    {
        "id": 27,
        "name_cn": "大阪府立大学",
        "name_en": "Osaka Prefecture University",
        "name_jp": "大阪府立大学",
        "style_logo": "",
        "long_logo": "",
        "sm_logo": "\/uploads\/schools\/sm_logo\/27.png",
        "cityid": 3518,
        "address": "堺市中区学園町1番1号",
        "website": "http:\/\/www.osakafu-u.ac.jp",
        "nature_id": 93,
        "nature_name": "公立",
        "contact": "4000150170",
        "rank_local": 28,
        "rank_world": 650
    },
    {
        "id": 28,
        "name_cn": "埼玉大学",
        "name_en": "Saitama University",
        "name_jp": "埼玉大学",
        "style_logo": "",
        "long_logo": "\/uploads\/schools\/long_logo\/28.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/28.png",
        "cityid": 3516,
        "address": "埼玉县樱市 下大久保地区255",
        "website": "http:\/\/www.saitama-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 41,
        "rank_world": 800
    },
    {
        "id": 29,
        "name_cn": "岐阜大学",
        "name_en": "Gifu University",
        "name_jp": "岐阜大学",
        "style_logo": "",
        "long_logo": "",
        "sm_logo": "\/uploads\/schools\/sm_logo\/29.png",
        "cityid": 3527,
        "address": "日本岐阜县岐阜市柳户1-1",
        "website": "http:\/\/www.gifu-u.ac.jp",
        "nature_id": 92,
        "nature_name": "国立",
        "contact": "4000150170",
        "rank_local": 72,
        "rank_world": 990
    },
    {
        "id": 30,
        "name_cn": "上智大学",
        "name_en": "Sophia University",
        "name_jp": "上智大学",
        "style_logo": "\/uploads\/20180821\/ea55ca6d0a7460f1b013c129b3400d77.jpg",
        "long_logo": "\/uploads\/schools\/long_logo\/30.png",
        "sm_logo": "\/uploads\/schools\/sm_logo\/30.png",
        "cityid": 3556,
        "address": "東京都千代田区紀尾井町７−１",
        "website": "http:\/\/www.sophia.ac.jp",
        "nature_id": 94,
        "nature_name": "私立",
        "contact": "4000150170",
        "rank_local": 29,
        "rank_world": 700
    }
];

const user = [
    {
        "name": "Betty Osinski Sr.",
        "email": "madge.krajcik@example.com",
        "phone": "(351) 245-3318 x2828",
        "gender": 1,
        "address": "92542 Blick Parkways\nDewittbury, CA 97302-5281",
        "status": 3,
        "country": "Bhutan"
    },
    {
        "name": "Reece Borer",
        "email": "lbergnaum@example.com",
        "phone": "298.568.8169",
        "gender": 1,
        "address": "60843 Madisyn Hollow Apt. 383\nSouth Nick, MT 81681",
        "status": 3,
        "country": "Zimbabwe"
    },
    {
        "name": "Augustus Conroy",
        "email": "mwolf@example.net",
        "phone": "556-806-5793 x8140",
        "gender": 2,
        "address": "89337 Ondricka Run\nKihnshire, AR 21097",
        "status": 4,
        "country": "Saint Martin"
    },
    {
        "name": "Dane Altenwerth",
        "email": "hill.pinkie@example.org",
        "phone": "1-940-219-1759 x175",
        "gender": 1,
        "address": "903 Lowe Stream\nWest Enidfort, IL 33013",
        "status": 2,
        "country": "Maldives"
    },
    {
        "name": "Mrs. Viola Muller V",
        "email": "haley.gladyce@example.org",
        "phone": "(208) 796-8202 x61367",
        "gender": 2,
        "address": "2746 Schowalter Courts\nHalvorsonmouth, ND 62514",
        "status": 2,
        "country": "Jordan"
    },
    {
        "name": "Krystina Christiansen",
        "email": "hayley99@example.net",
        "phone": "1-841-919-2358 x700",
        "gender": 1,
        "address": "802 Hudson Roads\nNew Roman, TX 74885",
        "status": 4,
        "country": "Canada"
    },
    {
        "name": "Odie Bernier",
        "email": "khuels@example.org",
        "phone": "(594) 462-5108",
        "gender": 2,
        "address": "80904 Osvaldo Loop Apt. 051\nStiedemannmouth, AK 65155",
        "status": 3,
        "country": "Latvia"
    },
    {
        "name": "Gwen Bernhard",
        "email": "vparisian@example.org",
        "phone": "993.967.3689",
        "gender": 2,
        "address": "412 Erick Avenue\nNorth Madalynmouth, NJ 26942-2867",
        "status": 1,
        "country": "Bouvet Island (Bouvetoya)"
    },
    {
        "name": "Dr. Joany Armstrong II",
        "email": "dee.schaefer@example.com",
        "phone": "416.912.3423 x903",
        "gender": 2,
        "address": "1266 Collier Well Suite 269\nPagacberg, VT 09352",
        "status": 2,
        "country": "Falkland Islands (Malvinas)"
    },
    {
        "name": "Webster Murray",
        "email": "leopoldo.lockman@example.net",
        "phone": "+14788677759",
        "gender": 1,
        "address": "493 Emelie Fork Apt. 979\nPort Destany, GA 09304",
        "status": 4,
        "country": "Kenya"
    },
    {
        "name": "Ophelia Bartoletti II",
        "email": "kohler.aurore@example.org",
        "phone": "+1 (982) 859-4850",
        "gender": 2,
        "address": "439 Geraldine Views Apt. 650\nNew Ernesto, CA 78879-6068",
        "status": 1,
        "country": "Grenada"
    },
    {
        "name": "Andre Effertz",
        "email": "dietrich.brandt@example.org",
        "phone": "1-349-723-3642 x21344",
        "gender": 2,
        "address": "13892 Lera Mall Apt. 074\nLake Marquis, PA 75238-6434",
        "status": 5,
        "country": "Iran"
    },
    {
        "name": "Giuseppe McLaughlin II",
        "email": "buckridge.deron@example.com",
        "phone": "(265) 842-9180 x85326",
        "gender": 1,
        "address": "5107 Cassie Falls Suite 906\nEast Reynold, ID 27216-5017",
        "status": 3,
        "country": "Pitcairn Islands"
    },
    {
        "name": "Dr. Cloyd Kris",
        "email": "schimmel.justen@example.org",
        "phone": "(543) 836-8677 x99917",
        "gender": 2,
        "address": "813 Evie Landing\nNew Eliezerville, OH 99555-5595",
        "status": 5,
        "country": "Bahamas"
    },
    {
        "name": "Demario Beatty PhD",
        "email": "bergnaum.jonathon@example.net",
        "phone": "790-299-5773",
        "gender": 2,
        "address": "733 Alek Expressway Apt. 882\nLake Keagan, NJ 62149",
        "status": 2,
        "country": "Guinea"
    },
    {
        "name": "Alize Russel",
        "email": "dewitt.pouros@example.com",
        "phone": "445.213.9167 x5000",
        "gender": 1,
        "address": "3697 Monahan Village\nEast Rossie, IA 80441",
        "status": 1,
        "country": "Cuba"
    },
    {
        "name": "Mr. Tito Gutmann",
        "email": "mireya.senger@example.org",
        "phone": "435-427-5968",
        "gender": 1,
        "address": "276 Hertha Way Suite 268\nNorth Dock, AL 34257",
        "status": 5,
        "country": "United States Minor Outlying Islands"
    },
    {
        "name": "Fabiola Predovic",
        "email": "chelsie.cronin@example.org",
        "phone": "(442) 626-8876 x7945",
        "gender": 2,
        "address": "140 Madaline Burg Suite 706\nNorth Michelleberg, NJ 08163-2407",
        "status": 1,
        "country": "Latvia"
    },
    {
        "name": "Lynn Rodriguez II",
        "email": "hudson.bernardo@example.org",
        "phone": "246.848.9813",
        "gender": 1,
        "address": "170 Kozey Orchard\nDinomouth, MN 44475-0795",
        "status": 1,
        "country": "Kuwait"
    },
    {
        "name": "Adolphus Denesik",
        "email": "conn.deon@example.com",
        "phone": "(469) 543-6561",
        "gender": 1,
        "address": "6267 Joana Isle Suite 466\nFadelstad, SD 65023",
        "status": 1,
        "country": "American Samoa"
    },
    {
        "name": "Mrs. Kathlyn Lemke III",
        "email": "qgorczany@example.com",
        "phone": "894-956-5510 x10815",
        "gender": 2,
        "address": "7088 Beier Forest\nJohnathonview, DE 64978-9563",
        "status": 1,
        "country": "Reunion"
    },
    {
        "name": "Ricardo Auer",
        "email": "kunde.ava@example.net",
        "phone": "1-663-264-3869",
        "gender": 1,
        "address": "9488 Lisa Harbor\nNew Tonyville, WV 22659-5315",
        "status": 4,
        "country": "Seychelles"
    },
    {
        "name": "Gerard Funk",
        "email": "mariam85@example.net",
        "phone": "925.853.6888 x959",
        "gender": 1,
        "address": "816 Schuppe Inlet Apt. 690\nEdwinshire, RI 99578-9076",
        "status": 3,
        "country": "Saint Pierre and Miquelon"
    },
    {
        "name": "Patsy Conn",
        "email": "vhills@example.com",
        "phone": "(345) 240-8477",
        "gender": 2,
        "address": "489 Guillermo Parkways Suite 334\nKarianneville, VA 07227",
        "status": 4,
        "country": "Canada"
    },
    {
        "name": "Tom Will",
        "email": "waters.jimmie@example.net",
        "phone": "424.335.8462",
        "gender": 1,
        "address": "194 Corkery Plaza\nWestberg, ND 08754-0532",
        "status": 4,
        "country": "Uruguay"
    },
    {
        "name": "Earlene Pollich",
        "email": "chet86@example.com",
        "phone": "850-284-0464",
        "gender": 2,
        "address": "5569 White Walk Apt. 364\nSusanafurt, AK 99246-1089",
        "status": 3,
        "country": "Guadeloupe"
    },
    {
        "name": "Chelsie Wilderman",
        "email": "ramon96@example.org",
        "phone": "507-791-1072",
        "gender": 1,
        "address": "553 Blaise Radial\nNorth Alleneland, MO 92126-0345",
        "status": 2,
        "country": "Samoa"
    },
    {
        "name": "Darrick Dietrich",
        "email": "kbashirian@example.org",
        "phone": "701.668.1412 x283",
        "gender": 1,
        "address": "3035 Ashley Trace Apt. 963\nSouth Tanyamouth, RI 71951-4994",
        "status": 1,
        "country": "Serbia"
    },
    {
        "name": "Eve Gutmann",
        "email": "tklocko@example.com",
        "phone": "562-605-3676",
        "gender": 1,
        "address": "3344 Brisa Island Apt. 564\nLake Fredericmouth, NM 41615",
        "status": 3,
        "country": "Norfolk Island"
    },
    {
        "name": "Ms. Breana Mills II",
        "email": "iernser@example.org",
        "phone": "662-990-4199 x2160",
        "gender": 1,
        "address": "4952 Bosco Pine Suite 645\nPort Mallory, IN 74611-8447",
        "status": 2,
        "country": "Nepal"
    }
];

module.exports = {school, user};